/** Model-visible closeout turn sent immediately before scratch compaction. */
export const SCRATCH_HANDOFF_CLOSEOUT_GUIDANCE =
	"This turn only prepares the handoff file. This file is the handoff itself: a colleague receives it immediately after this turn and continues the work from it, so write it for that colleague and keep stop, closeout, or end-of-turn instructions out of the file. Do not think through the task any further: write immediately from what you already know, as a snapshot of your current mind on the task — where it stands, what you have learned, and the thinking and planning already done toward next steps. Elide thinking and information that later work has superseded; keep the snapshot current, not complete. Write a useful draft checkpoint from the existing conversation evidence, then make targeted edits if needed. For an existing checkpoint, read it and update it in place. Start with an Active request heading: quote the latest substantive user request and later amendments, explain what a short confirmation such as yes approved, and state the next concrete action. Separate the active task from unrelated backlog and completed work. Record completed work, remaining TODOs, and blockers. Separate facts by host, repository, and path. Preserve uncertainty explicitly instead of repeatedly reconstructing the entire conversation from memory. Earlier thinking is tentative, not evidence that an action happened. Use prior tool results for disputed facts and leave unresolved checks for after compaction. Do not resume the underlying task during closeout. Finish after saving the file.";

export function renderScratchHandoffCloseoutMessage(displayPath: string, create = false): string {
	return create
		? `Stop working for now; please create a .org file brain-dump of your ongoing work to ${displayPath}, use org-todo structure including TODO subheadings, subheadings of subheadings, TODOs on nested subheadings, and so on. Do not think through the task any further: write immediately from what you already know. The file is a snapshot of your mind on this task — current progress, where things stand, and the thinking and planning done on next steps — so elide outdated or superseded thinking rather than preserving it. It should be detailed enough to hand off this work to a colleague. The file is the handoff itself: a colleague receives it immediately after this turn and continues the work from it, so keep stop, closeout, or end-of-turn instructions out of the file.`
		: `Stop working for now and make any final edits to ${displayPath} such that you can hand it to a colleague to continue this work. Do not think through the task any further: write immediately from what you already know. The file is a snapshot of your mind on this task — current progress, where things stand, and the thinking and planning done on next steps — so elide outdated or superseded thinking rather than preserving it. The file is the handoff itself: a colleague receives it immediately after this turn and continues the work from it, so keep stop, closeout, or end-of-turn instructions out of the file.`;
}
